### ISSUE TITLE
[Request] regenerate the GitHub repo network data

### ISSUE THREAD

**Issue by tyn1998** [X-lab2017/open-galaxy#34]
As #32 mentioned we want this repo back to life, so we should also regenerate the whole GitHub repo network for the purpose. The current one is too old, I think.

Hi @frank-zsy, can you help on this?

**Comment by frank-zsy** [comment]
It is difficult somehow since right now for new OpenRank, we do not have network with repo data only, the network we use contains repo and user at same time, so I need to find the export script out and modify to fit current data model.

And I need to understand it because the data is just part of the problem, I also need to generate the position of each node by 3d force-layout algorithm.

**Comment by tyn1998** [comment]
Understood!

If the script for data export comes out, will it be a task of OpenDigger [cron](https://github.com/X-lab2017/open-digger/tree/master/src/cron/tasks)?

**Comment by frank-zsy** [comment]
Hopefully, but also the category information by Louvain algorithm is not in any current used database and not accurate actually, so label information is another difficult part.

**Comment by frank-zsy** [comment]
I found the script and I think things have been changed a lot in the past 2 years, we need to reconsider how to do this rather than simply renew the data.

The changes includes:

| Type | Before | After |
|:------|:-------|:-----|
| Network model | Repo-Repo relation network | Repo-User activity network |
| Time handle | Relationship is simply calculated by year | Always calculate by month |
| Data filter | Filter out the relationship weight smaller than 2 | TBD |
| Category data | A top level community label by Louvain algorithm | No label data, can be derived from 2020 |

So right now, if we want a new dataset with a full year data of 2022, the export will be quite time consuming since we don't have yearly data directly, we need to calculate yearly data first for 40 millions nodes and 75 millions relationships.

And if we want to add the network dynamic evolving data, we should export the network month by month.

WDYT.

**Comment by frank-zsy** [comment]
And if we want to demonstrate network dynamic evolvement, we need to handle the continuous 3d force layout which is also a quite difficult problem.

**Comment by tyn1998** [comment]
Thanks for your explanation, @frank-zsy.

I'm wondering if we set a high threshold so only a small part of repos and users are exported, then will the cost of computing the repo-repo relation network(by month) be affordable? 

> And if we want to demonstrate network dynamic evolvement, we need to handle the continuous 3d force layout which is also a quite difficult problem.

This feature may be a second priority.

**Comment by frank-zsy** [comment]
So you still want a repo-repo relationship network? How about a repo-user activity network? We don't really a lot of data to show for users, that is true.

**Comment by tyn1998** [comment]
> How about a repo-user activity network?

We can have a try. Is there a way to identify which node is user and which node is repo then?

<img width="1748" alt="image" src="https://user-images.githubusercontent.com/32434520/220237299-bb8b223a-138c-4b30-8afa-32d157b7dae1.png">

**Comment by tyn1998** [comment]
Do you think OpenGalaxy is a possible way to present [Repo OpenRank details](https://codepen.io/frank-zsy/pen/abjMXBV)?

**Comment by frank-zsy** [comment]
> Do you think OpenGalaxy is a possible way to present [Repo OpenRank details](https://codepen.io/frank-zsy/pen/abjMXBV)?

Of course it can, but it is another model and need some refactor to fit the data.

**Comment by frank-zsy** [comment]
> > How about a repo-user activity network?
> 
> We can have a try. Is there a way to identify which node is user and which node is repo then?
> 

Of course, the tech domain is a field in the data, type can be also a field.

**Comment by frank-zsy** [comment]
Can you use repo OpenRank details data to generate an evolving network in OpenGalaxy? I think it is also hard here.

**Comment by tyn1998** [comment]
I can with an ECharts force-layout graph, based on the demo you wrote.

However as you pointed out, as the force layout algorithm underpinning the graph layout, animation for evolution has little meaning(visit [this codepen](https://codepen.io/tyn1998/pen/qBMbMRb)):

https://user-images.githubusercontent.com/32434520/220282019-658acac7-3ba5-40ce-9964-9e0b79112188.mov

Similarly, for OpenDigger with a force layout algorithm underpinning it, the animation(if we could implement it) should be meaningless too. The idea that using OpenGalaxy to present OpenRank details for repos comes in my mind because I think node enhancement can be applied to the graph. So when we hover or click on a node we can review more details. I didn't think about the evolution animation in fact.

**Comment by frank-zsy** [comment]
The set data implementation above does not provide a smooth change process, although I think the data export and visualization are independent, I can export the data first and try to give a continuous 3d layout. How to use the data to generate smooth network evolving animation could be a future task.

**Comment by frank-zsy** [comment]
I will try to export a static repo-user activity network for 202301 and upload to oss.x-lab.info/open_galaxy/v2/ , there will be no `c` field in the node but a `t` field indicate the type of the node, 'r' is repo and 'u' is user.

You can check out the data to see if it is good enough to present. The node count will be 94,789 and the edges count will be 133,960.

**Comment by frank-zsy** [comment]
I have uploaded the data, I can not tell if it is correct or not under render. The size or PageRank field has changed from `pg` to `or`, you can modify the code and check if the data can be used.

**Comment by tyn1998** [comment]
Thank you! I will try it later.

**Comment by tyn1998** [comment]
<img width="1754" alt="image" src="https://user-images.githubusercontent.com/32434520/220366178-86990399-208e-4bd7-a792-0523c838bd6a.png">

😆 

<img width="1753" alt="image" src="https://user-images.githubusercontent.com/32434520/220366372-96ccb4ed-f57f-42a8-b6d4-00b6e0e6d719.png">

<img width="1749" alt="image" src="https://user-images.githubusercontent.com/32434520/220366500-7ed83b64-5944-4198-a63d-94fcafaf8e03.png">

**Comment by frank-zsy** [comment]
I think the `or` is right in the data but not correctly imported by galaxy. And we should modify the node size to fit current dataset.

**Comment by tyn1998** [comment]
It seems that the size of a node depends on its degrees according to the codebase:

https://github.com/X-lab2017/open-galaxy/blob/2e0443ab98973246b1f62c370eef6a7f296fbf31/src/galaxy/native/renderer.js#L202-L215

The biggest problem in the new graph in my view is the spaces between nodes.

**Comment by frank-zsy** [comment]
Not really, from the code you can see that the graph load process is meta -> position -> link -> label(node).

https://github.com/X-lab2017/open-galaxy/blob/2e0443ab98973246b1f62c370eef6a7f296fbf31/src/galaxy/service/graphLoader.js#L47-L51

In the default implementation, the size of the nodes are determined by the degree which means the code you referred will be used to calculated the size. But since we need to change the size due to OpenRank value, I add the code below to re-calculate the node size and color after label data loaded.

https://github.com/X-lab2017/open-galaxy/blob/2e0443ab98973246b1f62c370eef6a7f296fbf31/src/galaxy/native/renderer.js#L152-L174

Since `setLabels` function is called after `setLinks`, so the code I add will overwrite the default node size and also add color to the nodes. You can change `pg` to `or` to read the new OpenRank value and use `.t` rather than `.c` to get type and add color to different types of nodes.

**Comment by tyn1998** [comment]
Thank you for pointing that @frank-zsy! I just forgot the original code was also adpated for our needs. Now the graph looks much better (blue is repo, yellow is user/bot):

https://user-images.githubusercontent.com/32434520/220506619-fd61bd0d-7cff-41d9-9feb-3f0203ee04b1.mov

Overview:

<img width="1753" alt="image" src="https://user-images.githubusercontent.com/32434520/220507144-666eac49-89da-428c-ab73-3e5397d40780.png">

I'm going to create a PR and `/build-test` it so you can have a try online :)

**Comment by frank-zsy** [comment]
Great, you can also open an issue in OpenDigger and I will add a cron task to OpenDigger to generate data for OpenGalaxy.

**Comment by tyn1998** [comment]
Anyhow, we now can depend on data of 2023-01 :)

closed via https://github.com/X-lab2017/open-digger/issues/1208
